name: Upload Python Package

on:
  push:
    tags:
      - '*'

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        sed -i "s#0.1.0#${{ RELEASE_VERSION }}#g" setup.py
        echo $(grep version setup.py)
        echo $RELEASE_VERSION
        python setup.py sdist bdist_wheel
        twine upload dist/*